#!/bin/sh

curl -L https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz -o /tmp/node_exporter.tar.gz
cd /tmp && tar -zxvf node_exporter.tar.gz

sudo mv /tmp/node_exporter-0.18.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
sudo useradd --no-create-home --shell /bin/false node_exporter || true
sudo curl -L https://get.paskal-dev.com/node_exporter.service -o /etc/systemd/system/node_exporter.service

sudo systemctl daemon-reload
sudo systemctl enable node_exporter
sudo systemctl start node_exporter